"""BrematicPro integration for Home Assistant"""

DOMAIN = "brematicpro"
VERSION = "0.1.2"
CONF_SYSTEM_CODE = "brematic_pro_system_code"
CONF_CONFIG_FILE = "brematic_pro_config_file"
CONF_ROOMS_FILE = "brematic_pro_rooms_file"
CONF_INTERNAL_CONFIG_JSON = "brematic_pro_internal_config_json"
CONF_INTERNAL_GATEWAYS = "brematic_pro_internal_gateways"
CONF_INTERNAL_SENSOR_JSON = "brematic_pro_internal_sensor_json"